services:
  caddy:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
      - "2015:2015"
    volumes:
      - $PWD/caddy/conf:/etc/caddy
      - $PWD/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - $PWD/demo-fake-api:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
